<?php

/**
 * @file
 * Main file for the Open Y Node Blog module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function openy_node_blog_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_blog_edit_form' || $form_id == 'node_blog_form') {
    $visible = [
      'visible' => [
        [
          'select[name="field_blog_style"]' => ['value' => 'color'],
        ],
      ],
    ];
    $form['field_blog_color']['widget']['#states'] = $visible;     
    $form['field_blog_text_color']['widget']['#states'] = $visible;
  }
}

/**
 * Implements hook_theme().
 */
function openy_node_blog_theme($existing, $type, $theme, $path) {
  return [
    'simple_pagination' => [
      'variables' => [
        'next_link' => '',
        'prev_link' => '',
        'wrapperClass' => '',
      ],
      'template' => 'simple-pagination',
    ],
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function openy_node_blog_preprocess_node(&$variables) {
  if ($variables['node']->getType() !== 'blog') {
    return;
  }

  $variables['pagination'] = \Drupal::service('openy_node_blog.blog_paginator')->build();
}
