<?php

/**
 * @file
 * Open Y Node install file.
 */

/**
 * Implement hook_install().
 */
function openy_menu_main_install() {
  $config_dir = \Drupal::service('extension.list.module')->getPath('openy_menu_main') . '/config/override/';
  // Import new configuration.
  $config_importer = \Drupal::service('openy_upgrade_tool.importer');
  $config_importer->setDirectory($config_dir);
  $config_importer->importConfigs([
    'system.menu.main',
  ]);
}
