<?php

/**
 * @file
 * Open Y Media module file.
 */

use Drupal\Component\Utility\Html;

/**
 * Prepares variables for entity embed container templates.
 *
 * Default template: entity-embed-container.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *     Properties used: #attributes, #children.
 */
function openy_media_preprocess_entity_embed_container(array &$variables) {
  $view_mode = $variables['element']['#context']['data-entity-embed-display'];
  // Make the view mode context CSS class name compatible.
  $variables['attributes']['class'][] = Html::cleanCssIdentifier($view_mode, [
    ':' => '-',
    '.' => '-',
    '_' => '-',
  ]);
}

/**
 * Implements hook_library_info_alter().
 */
function openy_media_library_info_alter(&$libraries, $extension) {
  if ($extension === 'blazy' && function_exists('libraries_get_path')) {
    $libraries['blazy']['js']['/' . libraries_get_path('blazy') . '/blazy.min.js']['attributes'] = [
      'defer' => TRUE,
    ];
  }
}

/**
 * Implements hook_blazy_attach_alter().
 */
function openy_media_blazy_attach_alter(array &$load, array $settings = []) {
  $load['library'][] = 'openy_media/blazy_ratio';
}
