<?php

/**
 * @file
 * Open Y Media Video module file.
 */

use Drupal\openy_media_video\OpenyMediaVideoPreRender;

/**
 * Implements hook_element_info_alter().
 */
function openy_media_video_element_info_alter(&$info) {
  if (isset($info['video_embed_iframe'])) {
    $info['video_embed_iframe']['#pre_render'][] =
      [
        OpenyMediaVideoPreRender::class, 'videoEmbedIframePrerender'
      ];
  }
}
